-- نقل الموظفين: طلب من مراقب الموقع الأصلي → موافقة مراقب الوجهة → اعتماد HR/أدمن
-- نفّذ في Supabase SQL Editor بعد التأكد من وجود public.app_users و public.sites و public.workers.

-- ربط المستخدمين بالمواقع (مراقب ميداني = مواقع مسؤوليته)
CREATE TABLE IF NOT EXISTS public.app_user_sites (
  app_user_id bigint NOT NULL REFERENCES public.app_users (id) ON DELETE CASCADE,
  site_id bigint NOT NULL REFERENCES public.sites (id) ON DELETE CASCADE,
  PRIMARY KEY (app_user_id, site_id)
);

CREATE INDEX IF NOT EXISTS idx_app_user_sites_site_id ON public.app_user_sites (site_id);

COMMENT ON TABLE public.app_user_sites IS 'المواقع التي يحق للمراقب الميداني رؤيتها/التحضير عليها؛ الأدمن يضيف الصفوف من واجهة المستخدمين لاحقاً.';

DO $$
BEGIN
  IF NOT EXISTS (SELECT 1 FROM pg_type WHERE typname = 'worker_transfer_status') THEN
    CREATE TYPE public.worker_transfer_status AS ENUM (
      'pending_destination',
      'rejected_destination',
      'pending_hr',
      'rejected_hr',
      'approved'
    );
  END IF;
END$$;

CREATE TABLE IF NOT EXISTS public.worker_transfer_requests (
  id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  worker_id bigint NOT NULL REFERENCES public.workers (id) ON DELETE CASCADE,
  from_site_id bigint REFERENCES public.sites (id) ON DELETE SET NULL,
  to_site_id bigint NOT NULL REFERENCES public.sites (id) ON DELETE CASCADE,
  requested_by_app_user_id bigint NOT NULL REFERENCES public.app_users (id) ON DELETE CASCADE,
  status public.worker_transfer_status NOT NULL DEFAULT 'pending_destination',
  destination_responded_by_app_user_id bigint REFERENCES public.app_users (id) ON DELETE SET NULL,
  destination_responded_at timestamptz,
  destination_note text,
  hr_responded_by_app_user_id bigint REFERENCES public.app_users (id) ON DELETE SET NULL,
  hr_responded_at timestamptz,
  hr_note text,
  created_at timestamptz NOT NULL DEFAULT now(),
  updated_at timestamptz NOT NULL DEFAULT now(),
  CONSTRAINT chk_wtr_sites_distinct CHECK (
    from_site_id IS NULL OR from_site_id <> to_site_id
  ),
  CONSTRAINT fk_wtr_from_site FOREIGN KEY (from_site_id) REFERENCES public.sites (id),
  CONSTRAINT fk_wtr_to_site FOREIGN KEY (to_site_id) REFERENCES public.sites (id)
);

CREATE INDEX IF NOT EXISTS idx_wtr_status ON public.worker_transfer_requests (status);
CREATE INDEX IF NOT EXISTS idx_wtr_to_site ON public.worker_transfer_requests (to_site_id);
CREATE INDEX IF NOT EXISTS idx_wtr_worker ON public.worker_transfer_requests (worker_id);

-- طلب واحد نشط (قيد التنفيذ) لكل عامل
CREATE UNIQUE INDEX IF NOT EXISTS idx_wtr_one_active_per_worker
  ON public.worker_transfer_requests (worker_id)
  WHERE status IN ('pending_destination', 'pending_hr');

-- التطبيق يستخدم مفتاح service_role (تجاوز RLS). يمكن لاحقاً إضافة سياسات لـ authenticated.
ALTER TABLE public.worker_transfer_requests ENABLE ROW LEVEL SECURITY;

GRANT ALL ON public.worker_transfer_requests TO service_role;
GRANT ALL ON public.app_user_sites TO service_role;
