-- Idempotency keys for offline/online attendance sync deduplication
create table if not exists public.sync_idempotency_keys (
  id bigint generated by default as identity primary key,
  idempotency_key text not null unique,
  action_scope text not null,
  created_at timestamptz not null default now()
);

create index if not exists idx_sync_idempotency_scope_created
  on public.sync_idempotency_keys(action_scope, created_at desc);
