-- جدول طلبات تعديل الحضور (شاشة «طلبات التعديل» + طلب المراقب الفني).
-- الخطأ: Could not find the table 'public.correction_requests' in the schema cache
-- نفّذ هذا الملف في Supabase → SQL Editor ثم: Settings → API → Reload schema (أو انتظر دقيقة).

create table if not exists public.correction_requests (
  id bigint generated by default as identity primary key,
  attendance_id bigint not null references public.attendance_checks (id) on delete cascade,
  requester_id bigint not null references public.app_users (id) on delete restrict,
  reason text,
  status text not null default 'pending'
    check (status in ('pending', 'approved', 'rejected')),
  created_at timestamptz not null default now()
);

create index if not exists idx_correction_requests_status on public.correction_requests (status);
create index if not exists idx_correction_requests_attendance on public.correction_requests (attendance_id);
create index if not exists idx_correction_requests_created on public.correction_requests (created_at desc);

comment on table public.correction_requests is 'طلبات تعديل حالة الحضور؛ pending حتى يعتمدها موارد/أدمن من شاشة طلبات التعديل.';

-- الوصول من التطبيق عبر service_role (createSupabaseAdminClient)؛ لا تضع مفتاح service_role في المتصفح.
grant select, insert, update, delete on public.correction_requests to service_role;
