-- Azzam Hajj System - Full bootstrap for new Supabase project
-- Safe to run multiple times (idempotent where possible).
--
-- مهم: app_users.role = text (ليس enum)؛ app.current_user_role() ترجع text؛ التحضير الجماعي = دالة واحدة
--       app.submit_attendance_bulk_checks(date,jsonb,text,integer) + public (انظر نهاية قسم RPCs).
--       مشروع **قائم** يحتاج بدلاً من هذه المرة الكاملة: `azzam-hajj-system/supabase_migration_app_users_role_to_text.sql`
--       راجع: `supabase_exec_order.sql` لترتيب الترقية.

begin;

create extension if not exists pgcrypto;

create schema if not exists app;

-- =========================
-- Enums
-- =========================
do $$
begin
  if not exists (select 1 from pg_type where typname = 'app_role') then
    create type public.app_role as enum ('admin', 'hr', 'technical_observer', 'field_observer');
  end if;
  if not exists (select 1 from pg_type where typname = 'attendance_status') then
    create type public.attendance_status as enum ('present', 'absent', 'half');
  end if;
  if not exists (select 1 from pg_type where typname = 'confirmation_status') then
    create type public.confirmation_status as enum ('pending', 'confirmed', 'rejected');
  end if;
  if not exists (select 1 from pg_type where typname = 'violation_severity') then
    create type public.violation_severity as enum ('low', 'medium', 'high', 'critical');
  end if;
  if not exists (select 1 from pg_type where typname = 'violation_status') then
    create type public.violation_status as enum ('pending_review', 'needs_more_info', 'approved', 'rejected');
  end if;
  if not exists (select 1 from pg_type where typname = 'violation_evidence_type') then
    create type public.violation_evidence_type as enum ('photo', 'text');
  end if;
end $$;

-- =========================
-- Utility trigger function
-- =========================
create or replace function app.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- =========================
-- Master tables
-- =========================
create table if not exists public.contractors (
  id bigint generated by default as identity primary key,
  name text not null unique,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.sites (
  id bigint generated by default as identity primary key,
  name text not null unique,
  main_contractor_id bigint references public.contractors(id) on delete set null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.app_users (
  id bigint generated by default as identity primary key,
  auth_user_id uuid unique references auth.users(id) on delete set null,
  username text not null unique,
  full_name text not null,
  -- مطابقة لـ user_roles.slug (نص حر، ليس enum)
  role text not null,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.user_sites (
  user_id bigint not null references public.app_users(id) on delete cascade,
  site_id bigint not null references public.sites(id) on delete cascade,
  created_at timestamptz not null default now(),
  primary key (user_id, site_id)
);

alter table public.app_users
  add column if not exists allowed_site_ids integer[] not null default '{}';

create table if not exists public.app_user_sites (
  app_user_id bigint not null references public.app_users(id) on delete cascade,
  site_id bigint not null references public.sites(id) on delete cascade,
  primary key (app_user_id, site_id)
);

create index if not exists idx_app_user_sites_site_id on public.app_user_sites (site_id);
create index if not exists idx_app_user_sites_app_user on public.app_user_sites (app_user_id);

-- =========================
-- user_roles: صلاحيات ديناميكية (مفاتيح + قيمة قديمة violations / violation_notice)
-- =========================
create table if not exists public.user_roles (
  id uuid primary key default gen_random_uuid(),
  slug text not null unique,
  name_ar text not null,
  permissions jsonb not null default '[]'::jsonb,
  created_at timestamptz default now()
);

insert into public.user_roles (slug, name_ar, permissions) values
(
  'admin',
  'مدير النظام',
  '["prep","approval","correction_request","workers_import","users_manage","roles_manage"]'::jsonb
),
(
  'hr',
  'الموارد البشرية',
  '["prep","approval","correction_request","workers_import","users_manage"]'::jsonb
),
(
  'technical_observer',
  'مراقب فني',
  '["dashboard","prep","approval","correction_request","corrections_screen","workers","sites","reports","violations","violation_notice"]'::jsonb
),
(
  'field_observer',
  'مراقب ميداني',
  '["prep","workers","sites","violations","violation_notice","transfers"]'::jsonb
)
on conflict (slug) do nothing;

alter table public.user_roles enable row level security;

drop policy if exists "user_roles_select_authenticated" on public.user_roles;
create policy "user_roles_select_authenticated"
  on public.user_roles
  for select
  to authenticated
  using (true);

create table if not exists public.workers (
  id bigint generated by default as identity primary key,
  name text not null,
  id_number text not null unique,
  job_title text,
  basic_salary numeric(12,2),
  payment_type text not null default 'salary' check (payment_type in ('salary', 'daily')),
  contractor_id bigint references public.contractors(id) on delete set null,
  current_site_id bigint references public.sites(id) on delete set null,
  assigned_supervisor_id bigint references public.app_users(id) on delete set null,
  iqama_expiry date,
  is_active boolean not null default true,
  is_deleted boolean not null default false,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_workers_current_site on public.workers(current_site_id);
create index if not exists idx_workers_contractor on public.workers(contractor_id);
create index if not exists idx_workers_active_not_deleted on public.workers(is_active, is_deleted);

alter table public.workers add column if not exists employee_code text;
comment on column public.workers.employee_code is 'كود الموظف — فريد عند التعبئة؛ يُدخل يدوياً أو من Excel';
create unique index if not exists idx_workers_employee_code_unique
  on public.workers ((btrim(employee_code)))
  where employee_code is not null and btrim(employee_code) <> '';

-- =========================
-- Attendance (round/check/summary)
-- =========================
create table if not exists public.attendance_rounds (
  id bigint generated by default as identity primary key,
  site_id bigint not null references public.sites(id) on delete restrict,
  work_date date not null,
  round_no integer not null check (round_no > 0),
  started_at timestamptz not null default now(),
  closed_at timestamptz,
  created_by bigint not null references public.app_users(id) on delete restrict,
  notes text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (site_id, work_date, round_no)
);

create index if not exists idx_att_rounds_site_date on public.attendance_rounds(site_id, work_date);
create index if not exists idx_att_rounds_creator on public.attendance_rounds(created_by);

create table if not exists public.attendance_checks (
  id bigint generated by default as identity primary key,
  round_id bigint not null references public.attendance_rounds(id) on delete cascade,
  worker_id bigint not null references public.workers(id) on delete restrict,
  status public.attendance_status not null,
  technical_observer_id bigint references public.app_users(id) on delete restrict,
  checked_at timestamptz not null default now(),
  confirmation_status public.confirmation_status not null default 'pending',
  field_observer_id bigint references public.app_users(id) on delete set null,
  confirmed_at timestamptz,
  confirm_note text,
  rejection_reason text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique (round_id, worker_id)
);

create index if not exists idx_att_checks_round on public.attendance_checks(round_id);
create index if not exists idx_att_checks_worker on public.attendance_checks(worker_id);
create index if not exists idx_att_checks_worker_date_status on public.attendance_checks(worker_id, confirmation_status);
create index if not exists idx_att_checks_pending on public.attendance_checks(confirmation_status, checked_at desc);

create table if not exists public.attendance_daily_summary (
  worker_id bigint not null references public.workers(id) on delete cascade,
  work_date date not null,
  site_id bigint references public.sites(id) on delete set null,
  total_rounds integer not null default 0,
  present_points numeric(8,2) not null default 0,
  absent_points numeric(8,2) not null default 0,
  half_points numeric(8,2) not null default 0,
  final_status public.attendance_status,
  last_confirmed_at timestamptz,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  primary key (worker_id, work_date)
);

create index if not exists idx_att_summary_date_site on public.attendance_daily_summary(work_date, site_id);
create index if not exists idx_att_summary_worker_date on public.attendance_daily_summary(worker_id, work_date);
create index if not exists idx_att_summary_site_date_final on public.attendance_daily_summary(site_id, work_date, final_status);

-- =========================
-- Violations
-- =========================
create table if not exists public.violation_types (
  id bigint generated by default as identity primary key,
  code text not null unique,
  name_ar text not null,
  name_en text,
  severity public.violation_severity not null default 'medium',
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create table if not exists public.worker_violations (
  id bigint generated by default as identity primary key,
  worker_id bigint not null references public.workers(id) on delete restrict,
  site_id bigint not null references public.sites(id) on delete restrict,
  violation_type_id bigint not null references public.violation_types(id) on delete restrict,
  description text,
  occurred_at timestamptz not null,
  reported_by bigint not null references public.app_users(id) on delete restrict,
  status public.violation_status not null default 'pending_review',
  reviewed_by bigint references public.app_users(id) on delete set null,
  reviewed_at timestamptz,
  review_note text,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now()
);

create index if not exists idx_worker_violations_worker_date on public.worker_violations(worker_id, occurred_at desc);
create index if not exists idx_worker_violations_status_site on public.worker_violations(status, site_id, occurred_at desc);
create index if not exists idx_worker_violations_reported_by on public.worker_violations(reported_by, occurred_at desc);

create table if not exists public.violation_evidence (
  id bigint generated by default as identity primary key,
  violation_id bigint not null references public.worker_violations(id) on delete cascade,
  evidence_type public.violation_evidence_type not null,
  storage_path text,
  text_body text,
  uploaded_by bigint not null references public.app_users(id) on delete restrict,
  created_at timestamptz not null default now(),
  constraint violation_evidence_payload_ck check (
    (evidence_type = 'photo' and storage_path is not null and text_body is null)
    or
    (evidence_type = 'text' and text_body is not null)
  )
);

create index if not exists idx_violation_evidence_violation on public.violation_evidence(violation_id);

create table if not exists public.violation_status_history (
  id bigint generated by default as identity primary key,
  violation_id bigint not null references public.worker_violations(id) on delete cascade,
  from_status public.violation_status,
  to_status public.violation_status not null,
  changed_by bigint not null references public.app_users(id) on delete restrict,
  note text,
  changed_at timestamptz not null default now()
);

create index if not exists idx_violation_status_history_violation on public.violation_status_history(violation_id, changed_at desc);

-- =========================
-- Update timestamps
-- =========================
drop trigger if exists trg_contractors_updated_at on public.contractors;
create trigger trg_contractors_updated_at before update on public.contractors
for each row execute function app.set_updated_at();

drop trigger if exists trg_sites_updated_at on public.sites;
create trigger trg_sites_updated_at before update on public.sites
for each row execute function app.set_updated_at();

drop trigger if exists trg_app_users_updated_at on public.app_users;
create trigger trg_app_users_updated_at before update on public.app_users
for each row execute function app.set_updated_at();

drop trigger if exists trg_workers_updated_at on public.workers;
create trigger trg_workers_updated_at before update on public.workers
for each row execute function app.set_updated_at();

drop trigger if exists trg_att_rounds_updated_at on public.attendance_rounds;
create trigger trg_att_rounds_updated_at before update on public.attendance_rounds
for each row execute function app.set_updated_at();

drop trigger if exists trg_att_checks_updated_at on public.attendance_checks;
create trigger trg_att_checks_updated_at before update on public.attendance_checks
for each row execute function app.set_updated_at();

drop trigger if exists trg_att_summary_updated_at on public.attendance_daily_summary;
create trigger trg_att_summary_updated_at before update on public.attendance_daily_summary
for each row execute function app.set_updated_at();

drop trigger if exists trg_violation_types_updated_at on public.violation_types;
create trigger trg_violation_types_updated_at before update on public.violation_types
for each row execute function app.set_updated_at();

drop trigger if exists trg_worker_violations_updated_at on public.worker_violations;
create trigger trg_worker_violations_updated_at before update on public.worker_violations
for each row execute function app.set_updated_at();

-- =========================
-- Auth helper functions
-- =========================
create or replace function app.current_user_id()
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select au.id
  from public.app_users au
  where au.auth_user_id = auth.uid()
  limit 1
$$;

create or replace function app.current_user_role()
returns text
language sql
stable
security definer
set search_path = public
as $$
  select au.role
  from public.app_users au
  where au.auth_user_id = auth.uid()
  limit 1
$$;

create or replace function app.current_user_site_ids()
returns bigint[]
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(
    (
      select array_agg(distinct sid order by sid)
      from (
        select aus.site_id as sid
        from public.app_user_sites aus
        join public.app_users au on au.id = aus.app_user_id
        where au.auth_user_id = auth.uid()
        union
        select us.site_id as sid
        from public.user_sites us
        join public.app_users au on au.id = us.user_id
        where au.auth_user_id = auth.uid()
        union
        select x::bigint as sid
        from public.app_users au
        cross join lateral unnest(coalesce(au.allowed_site_ids, '{}'::integer[])) as x
        where au.auth_user_id = auth.uid()
          and cardinality(coalesce(au.allowed_site_ids, '{}'::integer[])) > 0
      ) s
    ),
    '{}'::bigint[]
  )
$$;

create or replace function app.is_admin_or_hr()
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select coalesce(app.current_user_role() in ('admin', 'hr'), false)
$$;

-- مطابقة تقريبية لـ LEGACY_GRANTS في lib/permissions/keys.ts (المفاتيح المستخدمة في RLS فقط)
create or replace function app.has_granular_permission(p_required text)
returns boolean
language plpgsql
stable
security definer
set search_path = public
as $$
declare
  j jsonb;
begin
  if auth.uid() is null or p_required is null or length(trim(p_required)) = 0 then
    return false;
  end if;
  if not exists (select 1 from information_schema.tables where table_schema = 'public' and table_name = 'user_roles') then
    return false;
  end if;
  select ur.permissions into j
  from public.app_users au
  join public.user_roles ur on ur.slug = au.role
  where au.auth_user_id = auth.uid()
  limit 1;
  if j is null then
    return false;
  end if;
  if exists (
    select 1 from jsonb_array_elements_text(j) as e(perm) where e.perm = p_required
  ) then
    return true;
  end if;
  if p_required in ('view_violations', 'manage_violations') then
    if exists (select 1 from jsonb_array_elements_text(j) as e(perm) where e.perm = 'violations') then
      return true;
    end if;
  end if;
  if p_required = 'create_violation_notice' then
    if exists (select 1 from jsonb_array_elements_text(j) as e(perm) where e.perm = 'violation_notice') then
      return true;
    end if;
  end if;
  if p_required = 'report_violations' then
    if exists (select 1 from jsonb_array_elements_text(j) as e(perm) where e.perm in ('reports', 'view_reports')) then
      return true;
    end if;
  end if;
  -- مطابقة LEGACY_GRANTS: prep → view_attendance + edit_attendance
  if p_required in ('edit_attendance', 'view_attendance') then
    if exists (select 1 from jsonb_array_elements_text(j) as e(perm) where e.perm = 'prep') then
      return true;
    end if;
  end if;
  return false;
end;
$$;

grant execute on function app.has_granular_permission(text) to authenticated, service_role, anon;

create or replace function app.can_access_site(p_site_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    case
      when app.current_user_role() in ('admin', 'hr', 'technical_observer') then true
      else p_site_id = any(app.current_user_site_ids())
    end
$$;

create or replace function app.can_access_worker(p_worker_id bigint)
returns boolean
language sql
stable
security definer
set search_path = public
as $$
  select
    case
      when app.current_user_role() in ('admin', 'hr', 'technical_observer') then true
      else exists (
        select 1
        from public.workers w
        where w.id = p_worker_id
          and w.current_site_id is not null
          and w.current_site_id = any(app.current_user_site_ids())
      )
    end
$$;

-- =========================
-- Daily summary refresh
-- =========================
create or replace function app.refresh_attendance_daily_summary(p_worker_id bigint, p_work_date date)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_site_id bigint;
  v_total integer;
  v_present numeric(8,2);
  v_absent numeric(8,2);
  v_half numeric(8,2);
  v_final public.attendance_status;
  v_last_confirmed timestamptz;
begin
  select
    max(ar.site_id),
    count(*)::integer,
    coalesce(sum(case when ac.status = 'present' then 1 else 0 end), 0),
    coalesce(sum(case when ac.status = 'absent' then 1 else 0 end), 0),
    coalesce(sum(case when ac.status = 'half' then 1 else 0 end), 0),
    max(ac.confirmed_at)
  into v_site_id, v_total, v_present, v_absent, v_half, v_last_confirmed
  from public.attendance_checks ac
  join public.attendance_rounds ar on ar.id = ac.round_id
  where ac.worker_id = p_worker_id
    and ar.work_date = p_work_date
    and ac.confirmation_status = 'confirmed';

  if coalesce(v_total, 0) = 0 then
    delete from public.attendance_daily_summary
    where worker_id = p_worker_id and work_date = p_work_date;
    return;
  end if;

  if v_present >= greatest(v_absent, v_half) then
    v_final := 'present';
  elsif v_absent >= greatest(v_present, v_half) then
    v_final := 'absent';
  else
    v_final := 'half';
  end if;

  insert into public.attendance_daily_summary(
    worker_id, work_date, site_id, total_rounds,
    present_points, absent_points, half_points, final_status, last_confirmed_at
  )
  values (
    p_worker_id, p_work_date, v_site_id, v_total,
    v_present, v_absent, v_half, v_final, v_last_confirmed
  )
  on conflict (worker_id, work_date) do update
    set site_id = excluded.site_id,
        total_rounds = excluded.total_rounds,
        present_points = excluded.present_points,
        absent_points = excluded.absent_points,
        half_points = excluded.half_points,
        final_status = excluded.final_status,
        last_confirmed_at = excluded.last_confirmed_at,
        updated_at = now();
end;
$$;

create or replace function app.trg_refresh_attendance_daily_summary()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
declare
  v_worker_id bigint;
  v_work_date date;
begin
  if tg_op = 'DELETE' then
    v_worker_id := old.worker_id;
    select work_date into v_work_date from public.attendance_rounds where id = old.round_id;
  else
    v_worker_id := new.worker_id;
    select work_date into v_work_date from public.attendance_rounds where id = new.round_id;
  end if;

  if v_work_date is not null then
    perform app.refresh_attendance_daily_summary(v_worker_id, v_work_date);
  end if;

  return coalesce(new, old);
end;
$$;

drop trigger if exists trg_refresh_attendance_daily_summary on public.attendance_checks;
create trigger trg_refresh_attendance_daily_summary
after insert or update or delete on public.attendance_checks
for each row execute function app.trg_refresh_attendance_daily_summary();

-- =========================
-- Violation status history trigger
-- =========================
create or replace function app.trg_violation_status_history()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  if tg_op = 'INSERT' then
    insert into public.violation_status_history(violation_id, from_status, to_status, changed_by, note)
    values (new.id, null, new.status, new.reported_by, 'initial creation');
    return new;
  end if;

  if new.status is distinct from old.status then
    insert into public.violation_status_history(violation_id, from_status, to_status, changed_by, note)
    values (
      new.id,
      old.status,
      new.status,
      coalesce(new.reviewed_by, old.reviewed_by, new.reported_by),
      new.review_note
    );
  end if;
  return new;
end;
$$;

drop trigger if exists trg_violation_status_history_ins on public.worker_violations;
create trigger trg_violation_status_history_ins
after insert on public.worker_violations
for each row execute function app.trg_violation_status_history();

drop trigger if exists trg_violation_status_history_upd on public.worker_violations;
create trigger trg_violation_status_history_upd
after update of status on public.worker_violations
for each row execute function app.trg_violation_status_history();

-- =========================
-- RPCs
-- =========================
create or replace function app.start_attendance_round(
  p_site_id bigint,
  p_work_date date,
  p_round_no integer default null,
  p_notes text default null
)
returns public.attendance_rounds
language plpgsql
security definer
set search_path = public
as $$
declare
  v_creator_id bigint;
  v_role text;
  v_round_no integer;
  v_row public.attendance_rounds;
begin
  v_creator_id := app.current_user_id();
  v_role := app.current_user_role();

  if v_creator_id is null then
    raise exception 'Unauthorized user';
  end if;

  if v_role not in ('admin', 'hr', 'technical_observer')
     and not app.has_granular_permission('edit_attendance') then
    raise exception 'Only admin/hr/technical_observer can start rounds';
  end if;

  if not app.can_access_site(p_site_id) then
    raise exception 'No site access';
  end if;

  if p_round_no is null then
    select coalesce(max(round_no), 0) + 1
    into v_round_no
    from public.attendance_rounds
    where site_id = p_site_id
      and work_date = p_work_date;
  else
    v_round_no := p_round_no;
  end if;

  insert into public.attendance_rounds(site_id, work_date, round_no, created_by, notes)
  values (p_site_id, p_work_date, v_round_no, v_creator_id, p_notes)
  on conflict (site_id, work_date, round_no)
  do update set notes = excluded.notes
  returning * into v_row;

  return v_row;
end;
$$;

create or replace function app.submit_attendance_checks(
  p_round_id bigint,
  p_payload jsonb
)
returns table(inserted_count integer, updated_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_role text;
  v_site_id bigint;
  i_count integer := 0;
  u_count integer := 0;
begin
  v_user_id := app.current_user_id();
  v_role := app.current_user_role();
  if v_user_id is null then
    raise exception 'Unauthorized user';
  end if;
  if v_role not in ('admin', 'hr', 'technical_observer', 'field_observer')
     and not app.has_granular_permission('edit_attendance') then
    raise exception 'Only admin/hr/technical_observer/field_observer can submit checks';
  end if;

  select site_id into v_site_id
  from public.attendance_rounds
  where id = p_round_id;

  if v_site_id is null then
    raise exception 'Round not found';
  end if;

  if not app.can_access_site(v_site_id) then
    raise exception 'No site access';
  end if;

  with normalized_payload as (
    select distinct on (worker_id)
      worker_id,
      status
    from (
      select
        (item->>'worker_id')::bigint as worker_id,
        (item->>'status')::public.attendance_status as status,
        ordinality
      from jsonb_array_elements(p_payload) with ordinality as input(item, ordinality)
    ) raw
    where worker_id is not null and status is not null
    order by worker_id, ordinality desc
  ),
  allowed_payload as (
    select np.worker_id, np.status
    from normalized_payload np
    where app.can_access_worker(np.worker_id)
  ),
  updated_rows as (
    update public.attendance_checks ac
    set status = ap.status,
        technical_observer_id = case when v_role = 'field_observer' then null else v_user_id end,
        checked_at = now(),
        confirmation_status = 'pending',
        field_observer_id = case when v_role = 'field_observer' then v_user_id else null end,
        confirmed_at = null,
        confirm_note = null,
        rejection_reason = null
    from allowed_payload ap
    where ac.round_id = p_round_id
      and ac.worker_id = ap.worker_id
    returning ac.id
  ),
  inserted_rows as (
    insert into public.attendance_checks(
      round_id, worker_id, status, technical_observer_id, field_observer_id, checked_at, confirmation_status
    )
    select
      p_round_id,
      ap.worker_id,
      ap.status,
      case when v_role = 'field_observer' then null else v_user_id end,
      case when v_role = 'field_observer' then v_user_id else null end,
      now(),
      'pending'
    from allowed_payload ap
    left join public.attendance_checks ac
      on ac.round_id = p_round_id and ac.worker_id = ap.worker_id
    where ac.id is null
    returning id
  )
  select
    (select count(*)::integer from inserted_rows),
    (select count(*)::integer from updated_rows)
  into i_count, u_count;

  return query select i_count, u_count;
end;
$$;

-- إعادة تطبيق: احذف النسخة الثلاثية (date,jsonb,text) إن وُجدت حتى لا يتعارض النداء مع الافتراضي للرابع
drop function if exists app.submit_attendance_bulk_checks(date, jsonb, text);

-- تحضير جماعي بمعامل p_round_no (1=صباحي، 2=مسائي، …) — دالة app واحدة فقط
create or replace function app.submit_attendance_bulk_checks(
  p_work_date date,
  p_payload jsonb,
  p_notes text default null,
  p_round_no integer default 1
)
returns table(inserted_count integer, updated_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_role text;
  i_count integer := 0;
  u_count integer := 0;
  v_round integer;
begin
  v_round := greatest(1, least(coalesce(p_round_no, 1), 9));

  v_user_id := app.current_user_id();
  v_role := app.current_user_role();
  if v_user_id is null then
    raise exception 'Unauthorized user';
  end if;
  if v_role not in ('admin', 'hr', 'technical_observer', 'field_observer')
     and not app.has_granular_permission('edit_attendance') then
    raise exception 'Only admin/hr/technical_observer/field_observer can submit checks';
  end if;

  with normalized_payload as (
    select distinct on (worker_id)
      worker_id,
      status
    from (
      select
        (item->>'worker_id')::bigint as worker_id,
        (item->>'status')::public.attendance_status as status,
        ordinality
      from jsonb_array_elements(p_payload) with ordinality as input(item, ordinality)
    ) raw
    where worker_id is not null and status is not null
    order by worker_id, ordinality desc
  ),
  scoped_workers as (
    select
      np.worker_id,
      np.status,
      w.current_site_id as site_id
    from normalized_payload np
    join public.workers w on w.id = np.worker_id
    where w.current_site_id is not null
      and app.can_access_worker(np.worker_id)
      and app.can_access_site(w.current_site_id)
  ),
  ensure_rounds as (
    insert into public.attendance_rounds(site_id, work_date, round_no, created_by, notes)
    select
      sw.site_id,
      p_work_date,
      v_round,
      v_user_id,
      p_notes
    from (select distinct site_id from scoped_workers) sw
    on conflict (site_id, work_date, round_no)
    do update set notes = coalesce(excluded.notes, attendance_rounds.notes)
    returning id, site_id
  ),
  round_map as (
    select ar.id as round_id, ar.site_id
    from public.attendance_rounds ar
    join (select distinct site_id from scoped_workers) sw on sw.site_id = ar.site_id
    where ar.work_date = p_work_date
      and ar.round_no = v_round
  ),
  payload_with_round as (
    select
      sw.worker_id,
      sw.status,
      rm.round_id
    from scoped_workers sw
    join round_map rm on rm.site_id = sw.site_id
  ),
  updated_rows as (
    update public.attendance_checks ac
    set status = pwr.status,
        technical_observer_id = case when v_role = 'field_observer' then null else v_user_id end,
        checked_at = now(),
        confirmation_status = 'pending',
        field_observer_id = case when v_role = 'field_observer' then v_user_id else null end,
        confirmed_at = null,
        confirm_note = null,
        rejection_reason = null
    from payload_with_round pwr
    where ac.round_id = pwr.round_id
      and ac.worker_id = pwr.worker_id
    returning ac.id
  ),
  inserted_rows as (
    insert into public.attendance_checks(
      round_id, worker_id, status, technical_observer_id, field_observer_id, checked_at, confirmation_status
    )
    select
      pwr.round_id,
      pwr.worker_id,
      pwr.status,
      case when v_role = 'field_observer' then null else v_user_id end,
      case when v_role = 'field_observer' then v_user_id else null end,
      now(),
      'pending'
    from payload_with_round pwr
    left join public.attendance_checks ac
      on ac.round_id = pwr.round_id and ac.worker_id = pwr.worker_id
    where ac.id is null
    returning id
  )
  select
    (select count(*)::integer from inserted_rows),
    (select count(*)::integer from updated_rows)
  into i_count, u_count;

  return query select i_count, u_count;
end;
$$;

create or replace function public.submit_attendance_bulk_checks(
  p_work_date date,
  p_payload jsonb,
  p_notes text default null,
  p_round_no integer default 1
)
returns table(inserted_count integer, updated_count integer)
language sql
security definer
set search_path = public
as $$
  select * from app.submit_attendance_bulk_checks(p_work_date, p_payload, p_notes, p_round_no);
$$;

grant execute on function public.submit_attendance_bulk_checks(date, jsonb, text, integer)
to anon, authenticated, service_role;

-- توافق خلفي: استدعاء بثلاثة معاملات فقط يرسل وردية = 1 (تجنب غموض 42725)
create or replace function public.submit_attendance_bulk_checks(
  p_work_date date,
  p_payload jsonb,
  p_notes text default null
)
returns table(inserted_count integer, updated_count integer)
language sql
security definer
set search_path = public
as $$
  select * from app.submit_attendance_bulk_checks(p_work_date, p_payload, p_notes, 1);
$$;

grant execute on function public.submit_attendance_bulk_checks(date, jsonb, text)
to anon, authenticated, service_role;

create or replace function app.confirm_attendance_checks(
  p_round_id bigint,
  p_payload jsonb
)
returns table(confirmed_count integer, rejected_count integer)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user_id bigint;
  v_role text;
  v_site_id bigint;
  rec jsonb;
  v_worker_id bigint;
  v_action text;
  v_note text;
  c_count integer := 0;
  r_count integer := 0;
begin
  v_user_id := app.current_user_id();
  v_role := app.current_user_role();

  if v_user_id is null then
    raise exception 'Unauthorized user';
  end if;
  if v_role not in ('admin', 'hr', 'field_observer') then
    raise exception 'Only admin/hr/field_observer can confirm';
  end if;

  select site_id into v_site_id
  from public.attendance_rounds
  where id = p_round_id;

  if v_site_id is null then
    raise exception 'Round not found';
  end if;

  if not app.can_access_site(v_site_id) then
    raise exception 'No site access';
  end if;

  for rec in select * from jsonb_array_elements(p_payload)
  loop
    v_worker_id := (rec->>'worker_id')::bigint;
    v_action := lower(coalesce(rec->>'action', ''));
    v_note := rec->>'note';

    if v_action = 'confirm' then
      update public.attendance_checks
      set confirmation_status = 'confirmed',
          field_observer_id = v_user_id,
          confirmed_at = now(),
          confirm_note = v_note,
          rejection_reason = null
      where round_id = p_round_id and worker_id = v_worker_id;
      c_count := c_count + 1;
    elsif v_action = 'reject' then
      update public.attendance_checks
      set confirmation_status = 'rejected',
          field_observer_id = v_user_id,
          confirmed_at = now(),
          confirm_note = v_note,
          rejection_reason = coalesce(v_note, 'rejected by field observer')
      where round_id = p_round_id and worker_id = v_worker_id;
      r_count := r_count + 1;
    else
      raise exception 'Unknown action for worker %', v_worker_id;
    end if;
  end loop;

  return query select c_count, r_count;
end;
$$;

create or replace function app.get_monthly_attendance_matrix(
  p_year integer,
  p_month integer,
  p_site_id bigint default null,
  p_contractor_id bigint default null
)
returns table(
  worker_id bigint,
  worker_name text,
  id_number text,
  site_name text,
  d01 text, d02 text, d03 text, d04 text, d05 text, d06 text, d07 text, d08 text, d09 text, d10 text,
  d11 text, d12 text, d13 text, d14 text, d15 text, d16 text, d17 text, d18 text, d19 text, d20 text,
  d21 text, d22 text, d23 text, d24 text, d25 text, d26 text, d27 text, d28 text, d29 text, d30 text, d31 text,
  present_days numeric(8,2),
  absent_days numeric(8,2),
  half_days numeric(8,2)
)
language sql
stable
security definer
set search_path = public
as $$
with bounds as (
  select
    make_date(p_year, p_month, 1) as d_start,
    (make_date(p_year, p_month, 1) + interval '1 month' - interval '1 day')::date as d_end
),
base_workers as (
  select
    w.id,
    w.name as worker_name,
    w.id_number,
    s.name as site_name
  from public.workers w
  left join public.sites s on s.id = w.current_site_id
  where w.is_active = true
    and w.is_deleted = false
    and (p_site_id is null or w.current_site_id = p_site_id)
    and (p_contractor_id is null or w.contractor_id = p_contractor_id)
    and (app.is_admin_or_hr() or w.current_site_id = any(app.current_user_site_ids()))
),
agg as (
  select
    ads.worker_id,
    ads.work_date,
    case ads.final_status
      when 'present' then 'P'
      when 'absent' then 'A'
      when 'half' then 'H'
      else ''
    end as mark,
    ads.present_points,
    ads.absent_points,
    ads.half_points
  from public.attendance_daily_summary ads
  join bounds b on ads.work_date between b.d_start and b.d_end
)
select
  bw.id as worker_id,
  bw.worker_name,
  bw.id_number,
  bw.site_name,
  max(agg.mark) filter (where extract(day from agg.work_date) = 1) as d01,
  max(agg.mark) filter (where extract(day from agg.work_date) = 2) as d02,
  max(agg.mark) filter (where extract(day from agg.work_date) = 3) as d03,
  max(agg.mark) filter (where extract(day from agg.work_date) = 4) as d04,
  max(agg.mark) filter (where extract(day from agg.work_date) = 5) as d05,
  max(agg.mark) filter (where extract(day from agg.work_date) = 6) as d06,
  max(agg.mark) filter (where extract(day from agg.work_date) = 7) as d07,
  max(agg.mark) filter (where extract(day from agg.work_date) = 8) as d08,
  max(agg.mark) filter (where extract(day from agg.work_date) = 9) as d09,
  max(agg.mark) filter (where extract(day from agg.work_date) = 10) as d10,
  max(agg.mark) filter (where extract(day from agg.work_date) = 11) as d11,
  max(agg.mark) filter (where extract(day from agg.work_date) = 12) as d12,
  max(agg.mark) filter (where extract(day from agg.work_date) = 13) as d13,
  max(agg.mark) filter (where extract(day from agg.work_date) = 14) as d14,
  max(agg.mark) filter (where extract(day from agg.work_date) = 15) as d15,
  max(agg.mark) filter (where extract(day from agg.work_date) = 16) as d16,
  max(agg.mark) filter (where extract(day from agg.work_date) = 17) as d17,
  max(agg.mark) filter (where extract(day from agg.work_date) = 18) as d18,
  max(agg.mark) filter (where extract(day from agg.work_date) = 19) as d19,
  max(agg.mark) filter (where extract(day from agg.work_date) = 20) as d20,
  max(agg.mark) filter (where extract(day from agg.work_date) = 21) as d21,
  max(agg.mark) filter (where extract(day from agg.work_date) = 22) as d22,
  max(agg.mark) filter (where extract(day from agg.work_date) = 23) as d23,
  max(agg.mark) filter (where extract(day from agg.work_date) = 24) as d24,
  max(agg.mark) filter (where extract(day from agg.work_date) = 25) as d25,
  max(agg.mark) filter (where extract(day from agg.work_date) = 26) as d26,
  max(agg.mark) filter (where extract(day from agg.work_date) = 27) as d27,
  max(agg.mark) filter (where extract(day from agg.work_date) = 28) as d28,
  max(agg.mark) filter (where extract(day from agg.work_date) = 29) as d29,
  max(agg.mark) filter (where extract(day from agg.work_date) = 30) as d30,
  max(agg.mark) filter (where extract(day from agg.work_date) = 31) as d31,
  coalesce(sum(agg.present_points), 0)::numeric(8,2) as present_days,
  coalesce(sum(agg.absent_points), 0)::numeric(8,2) as absent_days,
  coalesce(sum(agg.half_points), 0)::numeric(8,2) as half_days
from base_workers bw
left join agg on agg.worker_id = bw.id
group by bw.id, bw.worker_name, bw.id_number, bw.site_name
order by bw.worker_name;
$$;

-- =========================
-- RLS
-- =========================
alter table public.contractors enable row level security;
alter table public.sites enable row level security;
alter table public.app_users enable row level security;
alter table public.user_sites enable row level security;
alter table public.workers enable row level security;
alter table public.attendance_rounds enable row level security;
alter table public.attendance_checks enable row level security;
alter table public.attendance_daily_summary enable row level security;
alter table public.violation_types enable row level security;
alter table public.worker_violations enable row level security;
alter table public.violation_evidence enable row level security;
alter table public.violation_status_history enable row level security;

-- app_users
drop policy if exists app_users_select_self_or_admin on public.app_users;
create policy app_users_select_self_or_admin on public.app_users
for select
using (
  app.is_admin_or_hr()
  or auth_user_id = auth.uid()
);

drop policy if exists app_users_admin_manage on public.app_users;
create policy app_users_admin_manage on public.app_users
for all
using (app.current_user_role() = 'admin')
with check (app.current_user_role() = 'admin');

-- user_sites
drop policy if exists user_sites_select_visible on public.user_sites;
create policy user_sites_select_visible on public.user_sites
for select
using (
  app.is_admin_or_hr()
  or site_id = any(app.current_user_site_ids())
);

drop policy if exists user_sites_admin_manage on public.user_sites;
create policy user_sites_admin_manage on public.user_sites
for all
using (app.current_user_role() = 'admin')
with check (app.current_user_role() = 'admin');

-- contractors / sites
drop policy if exists contractors_read_all on public.contractors;
create policy contractors_read_all on public.contractors
for select using (auth.uid() is not null);

drop policy if exists contractors_admin_hr_write on public.contractors;
create policy contractors_admin_hr_write on public.contractors
for all
using (app.is_admin_or_hr())
with check (app.is_admin_or_hr());

drop policy if exists sites_read_scoped on public.sites;
create policy sites_read_scoped on public.sites
for select
using (
  app.is_admin_or_hr()
  or id = any(app.current_user_site_ids())
);

drop policy if exists sites_admin_hr_write on public.sites;
create policy sites_admin_hr_write on public.sites
for all
using (app.is_admin_or_hr())
with check (app.is_admin_or_hr());

-- workers
drop policy if exists workers_read_scoped on public.workers;
create policy workers_read_scoped on public.workers
for select
using (
  app.is_admin_or_hr()
  or current_site_id = any(app.current_user_site_ids())
);

drop policy if exists workers_admin_hr_manage on public.workers;
create policy workers_admin_hr_manage on public.workers
for all
using (app.is_admin_or_hr())
with check (app.is_admin_or_hr());

-- attendance_rounds
drop policy if exists attendance_rounds_read_scoped on public.attendance_rounds;
create policy attendance_rounds_read_scoped on public.attendance_rounds
for select
using (
  app.is_admin_or_hr()
  or site_id = any(app.current_user_site_ids())
);

drop policy if exists attendance_rounds_create_technical on public.attendance_rounds;
create policy attendance_rounds_create_technical on public.attendance_rounds
for insert
with check (
  app.current_user_role() in ('admin', 'hr', 'technical_observer')
  and app.can_access_site(site_id)
);

drop policy if exists attendance_rounds_update_admin_hr_tech on public.attendance_rounds;
create policy attendance_rounds_update_admin_hr_tech on public.attendance_rounds
for update
using (
  app.current_user_role() in ('admin', 'hr', 'technical_observer')
  and app.can_access_site(site_id)
)
with check (
  app.current_user_role() in ('admin', 'hr', 'technical_observer')
  and app.can_access_site(site_id)
);

-- attendance_checks
drop policy if exists attendance_checks_read_scoped on public.attendance_checks;
create policy attendance_checks_read_scoped on public.attendance_checks
for select
using (
  app.is_admin_or_hr()
  or exists (
    select 1 from public.attendance_rounds ar
    where ar.id = attendance_checks.round_id
      and ar.site_id = any(app.current_user_site_ids())
  )
);

drop policy if exists attendance_checks_insert_technical on public.attendance_checks;
create policy attendance_checks_insert_technical on public.attendance_checks
for insert
with check (
  app.current_user_role() in ('admin', 'hr', 'technical_observer')
  and app.can_access_worker(worker_id)
  and exists (
    select 1 from public.attendance_rounds ar
    where ar.id = attendance_checks.round_id
      and app.can_access_site(ar.site_id)
  )
);

drop policy if exists attendance_checks_update_confirm on public.attendance_checks;
create policy attendance_checks_update_confirm on public.attendance_checks
for update
using (
  app.current_user_role() in ('admin', 'hr', 'technical_observer', 'field_observer')
  and exists (
    select 1 from public.attendance_rounds ar
    where ar.id = attendance_checks.round_id
      and app.can_access_site(ar.site_id)
  )
)
with check (
  app.current_user_role() in ('admin', 'hr', 'technical_observer', 'field_observer')
  and exists (
    select 1 from public.attendance_rounds ar
    where ar.id = attendance_checks.round_id
      and app.can_access_site(ar.site_id)
  )
);

drop policy if exists attendance_checks_no_delete_non_admin on public.attendance_checks;
create policy attendance_checks_no_delete_non_admin on public.attendance_checks
for delete
using (app.current_user_role() = 'admin');

-- attendance_daily_summary
drop policy if exists attendance_summary_read_scoped on public.attendance_daily_summary;
create policy attendance_summary_read_scoped on public.attendance_daily_summary
for select
using (
  app.is_admin_or_hr()
  or site_id = any(app.current_user_site_ids())
);

drop policy if exists attendance_summary_admin_manage on public.attendance_daily_summary;
create policy attendance_summary_admin_manage on public.attendance_daily_summary
for all
using (app.current_user_role() = 'admin')
with check (app.current_user_role() = 'admin');

-- violation types (عُرض الأنواع: مفتاح صلاحية وليس “أي مصادق”)
drop policy if exists violation_types_read_all on public.violation_types;
drop policy if exists violation_types_read_scoped on public.violation_types;
create policy violation_types_read_scoped on public.violation_types
for select
using (
  app.is_admin_or_hr()
  or app.has_granular_permission('view_violations')
  or app.has_granular_permission('manage_violations')
  or app.has_granular_permission('report_violations')
);

drop policy if exists violation_types_admin_hr_write on public.violation_types;
create policy violation_types_admin_hr_write on public.violation_types
for all
using (app.is_admin_or_hr())
with check (app.is_admin_or_hr());

-- worker violations (قيد النطاق: can_access_site — لا يعتمد على slug الدور)
drop policy if exists worker_violations_read_scoped on public.worker_violations;
create policy worker_violations_read_scoped on public.worker_violations
for select
using (
  app.is_admin_or_hr()
  or (
    (app.has_granular_permission('view_violations') or app.has_granular_permission('manage_violations'))
    and app.can_access_site(site_id)
  )
);

drop policy if exists worker_violations_insert_scoped on public.worker_violations;
create policy worker_violations_insert_scoped on public.worker_violations
for insert
with check (
  app.is_admin_or_hr()
  or (
    app.has_granular_permission('manage_violations')
    and app.can_access_site(site_id)
    and app.can_access_worker(worker_id)
  )
);

drop policy if exists worker_violations_update_review_scoped on public.worker_violations;
create policy worker_violations_update_review_scoped on public.worker_violations
for update
using (
  app.is_admin_or_hr()
  or (app.has_granular_permission('manage_violations') and app.can_access_site(site_id))
)
with check (
  app.is_admin_or_hr()
  or (app.has_granular_permission('manage_violations') and app.can_access_site(site_id))
);

-- لا حذف عبر PostgREST للمستخدمين — الحذف عبر service_role فقط
drop policy if exists worker_violations_no_delete on public.worker_violations;
create policy worker_violations_no_delete on public.worker_violations
for delete
using (false);

-- violation evidence
drop policy if exists violation_evidence_read_scoped on public.violation_evidence;
create policy violation_evidence_read_scoped on public.violation_evidence
for select
using (
  exists (
    select 1
    from public.worker_violations v
    where v.id = violation_evidence.violation_id
      and (
        app.is_admin_or_hr()
        or (
          (app.has_granular_permission('view_violations') or app.has_granular_permission('manage_violations'))
          and app.can_access_site(v.site_id)
        )
      )
  )
);

drop policy if exists violation_evidence_insert_scoped on public.violation_evidence;
create policy violation_evidence_insert_scoped on public.violation_evidence
for insert
with check (
  (app.is_admin_or_hr() or app.has_granular_permission('manage_violations'))
  and exists (
    select 1
    from public.worker_violations v
    where v.id = violation_evidence.violation_id
      and app.can_access_site(v.site_id)
  )
);

drop policy if exists violation_evidence_no_delete on public.violation_evidence;
create policy violation_evidence_no_delete on public.violation_evidence
for delete
using (false);

-- violation history
drop policy if exists violation_history_read_scoped on public.violation_status_history;
create policy violation_history_read_scoped on public.violation_status_history
for select
using (
  exists (
    select 1
    from public.worker_violations v
    where v.id = violation_status_history.violation_id
      and (
        app.is_admin_or_hr()
        or (
          (app.has_granular_permission('view_violations') or app.has_granular_permission('manage_violations'))
          and app.can_access_site(v.site_id)
        )
      )
  )
);

drop policy if exists violation_history_admin_manage on public.violation_status_history;
drop policy if exists violation_status_history_no_write on public.violation_status_history;
drop policy if exists violation_status_history_no_delete on public.violation_status_history;
drop policy if exists violation_status_history_insert_chain on public.violation_status_history;
create policy violation_status_history_no_write on public.violation_status_history
for update
using (false);
create policy violation_status_history_no_delete on public.violation_status_history
for delete
using (false);
-- إدراج تلقائي عبر الـ trigger: changed_by يطابق app_users للجلسة
create policy violation_status_history_insert_chain on public.violation_status_history
for insert
with check (
  app.current_user_id() is not null
  and changed_by = app.current_user_id()
);

-- =========================
-- Storage bucket for violation photos
-- =========================
-- هيكل المسار (عمود name داخل الـ bucket):
--   site_{site_id}/[فروع اختيارية/]الملف
--   مثال: site_12/abc.jpg  أو  site_12/2025/round1/photo.png
-- رفع/تحميل مكثف: دالة one-shot لاستخراج site_id؛ سياسة الرفع = manage_violations (ديناميكي) وليس slug الدور
insert into storage.buckets (id, name, public, file_size_limit, allowed_mime_types)
values (
  'violation-evidence',
  'violation-evidence',
  false,
  10485760,
  array['image/png', 'image/jpeg', 'image/webp']
)
on conflict (id) do nothing;

create or replace function app.violation_evidence_site_id_from_path(p_object_name text)
returns bigint
language sql
stable
security definer
set search_path = public
as $$
  select (regexp_match(split_part(p_object_name, '/', 1), '^site_([0-9]+)$'))[1]::bigint
$$;

grant execute on function app.violation_evidence_site_id_from_path(text) to authenticated, service_role, anon;

drop policy if exists violation_evidence_bucket_select on storage.objects;
create policy violation_evidence_bucket_select on storage.objects
for select
using (
  bucket_id = 'violation-evidence'
  and auth.uid() is not null
  and (
    app.is_admin_or_hr()
    or (
      app.violation_evidence_site_id_from_path(name) is not null
      and (app.has_granular_permission('view_violations') or app.has_granular_permission('manage_violations'))
      and app.can_access_site(app.violation_evidence_site_id_from_path(name))
    )
  )
);

drop policy if exists violation_evidence_bucket_insert on storage.objects;
create policy violation_evidence_bucket_insert on storage.objects
for insert
with check (
  bucket_id = 'violation-evidence'
  and auth.uid() is not null
  and app.violation_evidence_site_id_from_path(name) is not null
  and (app.is_admin_or_hr() or app.has_granular_permission('manage_violations'))
  and app.can_access_site(app.violation_evidence_site_id_from_path(name))
);

-- لا تعديل/حذف من الـ client — استخدم service_role (أو لوحة Supabase) للصيانة
drop policy if exists violation_evidence_bucket_update on storage.objects;
drop policy if exists violation_evidence_bucket_delete_admin on storage.objects;
drop policy if exists violation_evidence_bucket_no_update on storage.objects;
drop policy if exists violation_evidence_bucket_no_delete on storage.objects;
create policy violation_evidence_bucket_no_update on storage.objects
for update
using (false);
create policy violation_evidence_bucket_no_delete on storage.objects
for delete
using (false);

-- =========================
-- Seed data (idempotent)
-- =========================
insert into public.violation_types(code, name_ar, name_en, severity)
values
  ('no_uniform', 'عدم الالتزام بالزي', 'Uniform violation', 'medium'),
  ('late_arrival', 'تأخر عن الحضور', 'Late arrival', 'low'),
  ('left_site', 'مغادرة الموقع بدون إذن', 'Left site without approval', 'high'),
  ('safety_violation', 'مخالفة اشتراطات السلامة', 'Safety violation', 'critical'),
  ('insubordination', 'عدم الامتثال للتوجيهات', 'Insubordination', 'high')
on conflict (code) do nothing;

commit;

